### ISSUE TITLE
Q: Is it possible to disable the feature where the robot explodes if out of bounds?

### ISSUE THREAD

**Issue by nettercm** [ron-grant/LFS#2]
Previously it was possible to simply reposition the robot back onto the track, even after it went completely off-grid.  This helps with experimentation.

**Comment by ron-grant** [comment]
yes go to the uMisc tab  comment out the code in the method defined there. Leave the method.On Oct 21, 2020 3:41 PM, "Christian M. Netter" <notifications@github.com> wrote:
Previously it was possible to simply reposition the robot back onto the track, even after it went completely off-grid.  This helps with experimentation.

**Comment by ron-grant** [comment]
Also, if you right click on userOutOfBounds method in uMisc you will be able to see references to that method. Do that and click on the calling ref. You will find commands that stop robot. Comment out to let robot keep running when out of bounds. On Oct 21, 2020 3:41 PM, "Christian M. Netter" <notifications@github.com> wrote:
Previously it was possible to simply reposition the robot back onto the track, even after it went completely off-grid.  This helps with experimentation.

**Comment by ron-grant** [comment]
That is right click on method name. On Oct 22, 2020 3:21 AM, deltagraph@aol.com wrote:Also, if you right click on userOutOfBounds method in uMisc you will be able to see references to that method. Do that and click on the calling ref. You will find commands that stop robot. Comment out to let robot keep running when out of bounds. On Oct 21, 2020 3:41 PM, "Christian M. Netter" <notifications@github.com> wrote:
Previously it was possible to simply reposition the robot back onto the track, even after it went completely off-grid.  This helps with experimentation.

**Comment by nettercm** [comment]
It seems that one must close the parameters panel immediately after adjusting a parameter.  Otherwise, mouse movement/clicks that take place outside the parameters window end up changing a parameter - and this can go unnoticed and hence cause much confusion....

**Comment by ron-grant** [comment]
Hello Chris, Getting close on update that fixes a number of problems - working on Lap timer

Line Following Simulator  1.4.1 to be released by this afternoon - I hope


BUGS

Demo sketch problems 

  Fixed Parameter Editor allowing changes when Editor not visible, or mouse  
  outside view port. (Thanks Chris N for reporting problem)
 
  Fixed Integer parameter number format error.  

  Disabled sound by default uMisc. Instructions there for importing Sound library.
  This removes need to download sound library - if you don't care about sound... 

 Added stopOnOutOfBounds boolean to uMisc 
 When set false robot will contine to run when outof bounds 

 Eliminated "turn off controller" on out of bounds (Thanks again Chris N)
 will allow you to move robot back on to course when not running in contest mode.
 i.e. G)o command
 
Fixed problem with  userOutOfBounds blanking Command Summary  panel



NEW FEATURES 

 Added Simulator Max values to a new help page 

Optional  report and/or show how far robot has traveled:
  Added two variables to LFS UserInit   (default is false for compatiblity with  (lib 1.3.1)
    contestReportIncludesDist 
    showDistanceTraveled 
  (May change location so as not to affect UserCode (UserCon,UserInit,UserReset,UserDraw tabs)


 IN PROCESS

Working on automatic Lap Times for novice and advanced contest.
After robot travels distance > 10 inches from start, stop trigger is set.
When robot closer to start point than X inches (e.g. 3) lap time recorded.

There will be some kind of user set control e.g.  enableLapTimer, which will be false
for challenge course, true for Novice and Advanced.

I will probably add few lines to userInit
that includes all three courses with proper setting for enableLapTimer
