### ISSUE TITLE
Its easy to cause accidental parameter adjustment

### ISSUE THREAD

**Issue by nettercm** [ron-grant/LFS#3]
It seems that one must close the parameters panel immediately after adjusting a parameter. Otherwise, mouse movement/clicks that take place outside the parameters window end up changing a parameter - and this can go unnoticed and hence cause much confusion....

**Comment by ron-grant** [comment]
Thanks, Chris, This has been fixed also issue with Ctrl-A default all not working - fixed in v1.5.1
