### ISSUE TITLE
Bug:  the center element of my line sensor array always reads value 0.84, even if its on top of solid black

### ISSUE THREAD

**Issue by nettercm** [ron-grant/LFS#4]
I have a line sensor of 33 elements and spot size of 20x20.   the center element always reads a value of 0.84, regardless of what's underneath.   I'm worried that this will confuse my logic.  Using version 1.4 from lineFollowerSim-5.zip

**Comment by nettercm** [comment]
If the spot size is reduced to 5x5, the issue is still there but now the value is fixed at 0.46

**Comment by ron-grant** [comment]
I have this problem fixed. I promise I will do a push this afternoon along with parameter editor fix + added auto lap detection.  Higher frame rate is result too.  In my case  ~50% faster. If I knew what I was doing with git I would create a branch... Soon I will know what to do...

**Comment by ron-grant** [comment]
OK, I pushed 1.4.1.  for second time just now (first time old SampleBot)   You will need to drop your code into new SampleBot  in Examples...

**Comment by ron-grant** [comment]
You will need to set chooseCourse.. to (3) in userInit.  New feature, list of courses where you can select initial. Also, Ctrl-C to advance to next course.  Now simulator reports distance traveled, but not accessible. Later will be accessible after run stops.
Thought is might be possible to implement automated multi-run tuning...

**Comment by ron-grant** [comment]
Pushed Version 1.4.2 which fixes line sensor elements not reading correctly. I believe problem is 1 pixel overlap among spot sensors arranged in straight line. Did not address overlap but did remove what amounted to destructive read where pixels were colored as they were read versus completing all reading then following with coloring.
