### ISSUE TITLE
setRotation() doesn't seem to work right for straight line sensors

### ISSUE THREAD

**Issue by nettercm** [ron-grant/LFS#6]
So I'd like my line sensor to be parallel to the wheels, i.e. perpendicular to the wheel axle.  
setRotation(0.30155) seems to do the trick, but why 0.30155 and not 90 ?
a tiny change to the parameter passed into setRotation() seems to result in a major change in the line's angle

**Comment by ron-grant** [comment]
Chris,  Thanks. I inverted multiplier on conversion from degrees to radians,  180/PI vs    PI/180.Will be fixed shortly,so  you will need to correct your code on next release I will push in next few hours. 
-----Original Message-----

**Comment by nettercm** [comment]
Not high priority since I have a workaround...

Chris

On Nov 13, 2020, at 5:45 PM, Ron Grant <notifications@github.com> wrote:

﻿
Chris,  Thanks. I inverted multiplier on conversion from degrees to radians,  180/PI vs    PI/180.Will be fixed shortly,so  you will need to correct your code on next release I will push in next few hours. 
-----Original Message-----

**Comment by ron-grant** [comment]
Fixed in 1.6.4.
